__version__ = "0.1.0"
__author__ = "Arif Malik"
__license__ = "MIT"
__copyright__ = "Copyright 2020, Arif Malik"
__maintainer__ = "Arif Malik"
__email__ = "malikarif13@gmail.com"
__status__ = "Development"
